# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import meet_manager_pb2 as meet__manager__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meet_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeetManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeets = channel.unary_unary(
                '/meetmanager.MeetManagerService/GetMeets',
                request_serializer=meet__manager__pb2.Empty.SerializeToString,
                response_deserializer=meet__manager__pb2.MeetList.FromString,
                _registered_method=True)
        self.GetDashboardStats = channel.unary_unary(
                '/meetmanager.MeetManagerService/GetDashboardStats',
                request_serializer=meet__manager__pb2.Empty.SerializeToString,
                response_deserializer=meet__manager__pb2.DashboardStats.FromString,
                _registered_method=True)
        self.GetTeams = channel.unary_unary(
                '/meetmanager.MeetManagerService/GetTeams',
                request_serializer=meet__manager__pb2.Empty.SerializeToString,
                response_deserializer=meet__manager__pb2.TeamList.FromString,
                _registered_method=True)
        self.GetTeam = channel.unary_unary(
                '/meetmanager.MeetManagerService/GetTeam',
                request_serializer=meet__manager__pb2.TeamRequest.SerializeToString,
                response_deserializer=meet__manager__pb2.Team.FromString,
                _registered_method=True)
        self.GetAthletes = channel.unary_unary(
                '/meetmanager.MeetManagerService/GetAthletes',
                request_serializer=meet__manager__pb2.Empty.SerializeToString,
                response_deserializer=meet__manager__pb2.AthleteList.FromString,
                _registered_method=True)
        self.GetAthlete = channel.unary_unary(
                '/meetmanager.MeetManagerService/GetAthlete',
                request_serializer=meet__manager__pb2.AthleteRequest.SerializeToString,
                response_deserializer=meet__manager__pb2.Athlete.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/meetmanager.MeetManagerService/GetEvents',
                request_serializer=meet__manager__pb2.Empty.SerializeToString,
                response_deserializer=meet__manager__pb2.EventList.FromString,
                _registered_method=True)


class MeetManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMeets(self, request, context):
        """Meet Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboardStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeams(self, request, context):
        """Team Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAthletes(self, request, context):
        """Athlete Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAthlete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Event Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeetManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeets,
                    request_deserializer=meet__manager__pb2.Empty.FromString,
                    response_serializer=meet__manager__pb2.MeetList.SerializeToString,
            ),
            'GetDashboardStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardStats,
                    request_deserializer=meet__manager__pb2.Empty.FromString,
                    response_serializer=meet__manager__pb2.DashboardStats.SerializeToString,
            ),
            'GetTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeams,
                    request_deserializer=meet__manager__pb2.Empty.FromString,
                    response_serializer=meet__manager__pb2.TeamList.SerializeToString,
            ),
            'GetTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeam,
                    request_deserializer=meet__manager__pb2.TeamRequest.FromString,
                    response_serializer=meet__manager__pb2.Team.SerializeToString,
            ),
            'GetAthletes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAthletes,
                    request_deserializer=meet__manager__pb2.Empty.FromString,
                    response_serializer=meet__manager__pb2.AthleteList.SerializeToString,
            ),
            'GetAthlete': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAthlete,
                    request_deserializer=meet__manager__pb2.AthleteRequest.FromString,
                    response_serializer=meet__manager__pb2.Athlete.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=meet__manager__pb2.Empty.FromString,
                    response_serializer=meet__manager__pb2.EventList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meetmanager.MeetManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meetmanager.MeetManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeetManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMeets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.MeetManagerService/GetMeets',
            meet__manager__pb2.Empty.SerializeToString,
            meet__manager__pb2.MeetList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboardStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.MeetManagerService/GetDashboardStats',
            meet__manager__pb2.Empty.SerializeToString,
            meet__manager__pb2.DashboardStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.MeetManagerService/GetTeams',
            meet__manager__pb2.Empty.SerializeToString,
            meet__manager__pb2.TeamList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.MeetManagerService/GetTeam',
            meet__manager__pb2.TeamRequest.SerializeToString,
            meet__manager__pb2.Team.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAthletes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.MeetManagerService/GetAthletes',
            meet__manager__pb2.Empty.SerializeToString,
            meet__manager__pb2.AthleteList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAthlete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.MeetManagerService/GetAthlete',
            meet__manager__pb2.AthleteRequest.SerializeToString,
            meet__manager__pb2.Athlete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.MeetManagerService/GetEvents',
            meet__manager__pb2.Empty.SerializeToString,
            meet__manager__pb2.EventList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
