# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from meetmanager.v1 import meet_manager_pb2 as meetmanager_dot_v1_dot_meet__manager__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meetmanager/v1/meet_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeetManagerServiceStub(object):
    """MeetManagerService provides operations for managing swim meets, teams, athletes, and events.
    Meet Operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeets = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetMeets',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetMeetsRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetMeetsResponse.FromString,
                _registered_method=True)
        self.GetDashboardStats = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetDashboardStats',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetDashboardStatsRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetDashboardStatsResponse.FromString,
                _registered_method=True)
        self.GetTeams = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetTeams',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamsRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamsResponse.FromString,
                _registered_method=True)
        self.GetTeam = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetTeam',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamResponse.FromString,
                _registered_method=True)
        self.GetAthletes = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetAthletes',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthletesRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthletesResponse.FromString,
                _registered_method=True)
        self.GetAthlete = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetAthlete',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthleteRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthleteResponse.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetEvents',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventsResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/ListDatasets',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.SetActiveDataset = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/SetActiveDataset',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.SetActiveDatasetRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.SetActiveDatasetResponse.FromString,
                _registered_method=True)
        self.UploadDataset = channel.stream_unary(
                '/meetmanager.v1.MeetManagerService/UploadDataset',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.UploadDatasetRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.UploadDatasetResponse.FromString,
                _registered_method=True)
        self.ClearDataset = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/ClearDataset',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearDatasetRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearDatasetResponse.FromString,
                _registered_method=True)
        self.ClearAllDatasets = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/ClearAllDatasets',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearAllDatasetsRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearAllDatasetsResponse.FromString,
                _registered_method=True)
        self.GetRelays = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetRelays',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetRelaysRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetRelaysResponse.FromString,
                _registered_method=True)
        self.GetScores = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetScores',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetScoresRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetScoresResponse.FromString,
                _registered_method=True)
        self.GetEntries = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetEntries',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEntriesRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEntriesResponse.FromString,
                _registered_method=True)
        self.GetSessions = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetSessions',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetSessionsRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetSessionsResponse.FromString,
                _registered_method=True)
        self.GetAdminConfig = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetAdminConfig',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAdminConfigRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAdminConfigResponse.FromString,
                _registered_method=True)
        self.UpdateAdminConfig = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/UpdateAdminConfig',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.UpdateAdminConfigRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.UpdateAdminConfigResponse.FromString,
                _registered_method=True)
        self.GetEventScores = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GetEventScores',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventScoresRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventScoresResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/meetmanager.v1.MeetManagerService/GenerateReport',
                request_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GenerateReportRequest.SerializeToString,
                response_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GenerateReportResponse.FromString,
                _registered_method=True)


class MeetManagerServiceServicer(object):
    """MeetManagerService provides operations for managing swim meets, teams, athletes, and events.
    Meet Operations
    """

    def GetMeets(self, request, context):
        """GetMeets retrieves a list of all swim meets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDashboardStats(self, request, context):
        """GetDashboardStats retrieves summary statistics for the active meet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeams(self, request, context):
        """Team Operations

        GetTeams retrieves a list of all teams in the active meet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeam(self, request, context):
        """GetTeam retrieves details for a specific team by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAthletes(self, request, context):
        """Athlete Operations

        GetAthletes retrieves a list of athletes, optionally filtered by team ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAthlete(self, request, context):
        """GetAthlete retrieves details for a specific athlete by their ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Event Operations

        GetEvents retrieves a list of all events in the active meet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Admin Operations

        ListDatasets retrieves a list of available MDB datasets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiveDataset(self, request, context):
        """SetActiveDataset sets the specified MDB file as the active dataset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDataset(self, request_iterator, context):
        """UploadDataset uploads a new MDB dataset file as a stream of chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearDataset(self, request, context):
        """ClearDataset removes a specific dataset file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearAllDatasets(self, request, context):
        """ClearAllDatasets removes all uploaded dataset files.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelays(self, request, context):
        """New Data Operations

        GetRelays retrieves a list of all relay entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScores(self, request, context):
        """GetScores retrieves the current team scores.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntries(self, request, context):
        """GetEntries retrieves individual race entries, optionally filtered by athlete or event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessions(self, request, context):
        """Session Operations

        GetSessions retrieves a list of all sessions in the meet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminConfig(self, request, context):
        """Configuration

        GetAdminConfig retrieves the current administrative configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAdminConfig(self, request, context):
        """UpdateAdminConfig updates the administrative configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventScores(self, request, context):
        """GetEventScores retrieves scores for events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """GenerateReport generates a swim meet report (e.g., Psych Sheet, Results).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeetManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeets,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetMeetsRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetMeetsResponse.SerializeToString,
            ),
            'GetDashboardStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardStats,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetDashboardStatsRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetDashboardStatsResponse.SerializeToString,
            ),
            'GetTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeams,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamsRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamsResponse.SerializeToString,
            ),
            'GetTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeam,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamResponse.SerializeToString,
            ),
            'GetAthletes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAthletes,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthletesRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthletesResponse.SerializeToString,
            ),
            'GetAthlete': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAthlete,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthleteRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAthleteResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventsRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventsResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.ListDatasetsRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'SetActiveDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiveDataset,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.SetActiveDatasetRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.SetActiveDatasetResponse.SerializeToString,
            ),
            'UploadDataset': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadDataset,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.UploadDatasetRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.UploadDatasetResponse.SerializeToString,
            ),
            'ClearDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearDataset,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearDatasetRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearDatasetResponse.SerializeToString,
            ),
            'ClearAllDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearAllDatasets,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearAllDatasetsRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.ClearAllDatasetsResponse.SerializeToString,
            ),
            'GetRelays': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelays,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetRelaysRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetRelaysResponse.SerializeToString,
            ),
            'GetScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScores,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetScoresRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetScoresResponse.SerializeToString,
            ),
            'GetEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntries,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEntriesRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEntriesResponse.SerializeToString,
            ),
            'GetSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessions,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetSessionsRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetSessionsResponse.SerializeToString,
            ),
            'GetAdminConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminConfig,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAdminConfigRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetAdminConfigResponse.SerializeToString,
            ),
            'UpdateAdminConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAdminConfig,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.UpdateAdminConfigRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.UpdateAdminConfigResponse.SerializeToString,
            ),
            'GetEventScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventScores,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventScoresRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GetEventScoresResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=meetmanager_dot_v1_dot_meet__manager__pb2.GenerateReportRequest.FromString,
                    response_serializer=meetmanager_dot_v1_dot_meet__manager__pb2.GenerateReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meetmanager.v1.MeetManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meetmanager.v1.MeetManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeetManagerService(object):
    """MeetManagerService provides operations for managing swim meets, teams, athletes, and events.
    Meet Operations
    """

    @staticmethod
    def GetMeets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetMeets',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetMeetsRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetMeetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDashboardStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetDashboardStats',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetDashboardStatsRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetDashboardStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetTeams',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamsRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetTeam',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAthletes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetAthletes',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetAthletesRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetAthletesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAthlete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetAthlete',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetAthleteRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetAthleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetEvents',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetEventsRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/ListDatasets',
            meetmanager_dot_v1_dot_meet__manager__pb2.ListDatasetsRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActiveDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/SetActiveDataset',
            meetmanager_dot_v1_dot_meet__manager__pb2.SetActiveDatasetRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.SetActiveDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDataset(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/meetmanager.v1.MeetManagerService/UploadDataset',
            meetmanager_dot_v1_dot_meet__manager__pb2.UploadDatasetRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.UploadDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/ClearDataset',
            meetmanager_dot_v1_dot_meet__manager__pb2.ClearDatasetRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.ClearDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearAllDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/ClearAllDatasets',
            meetmanager_dot_v1_dot_meet__manager__pb2.ClearAllDatasetsRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.ClearAllDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetRelays',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetRelaysRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetRelaysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetScores',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetScoresRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetEntries',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetEntriesRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetSessions',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetSessionsRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetAdminConfig',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetAdminConfigRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetAdminConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAdminConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/UpdateAdminConfig',
            meetmanager_dot_v1_dot_meet__manager__pb2.UpdateAdminConfigRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.UpdateAdminConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GetEventScores',
            meetmanager_dot_v1_dot_meet__manager__pb2.GetEventScoresRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GetEventScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meetmanager.v1.MeetManagerService/GenerateReport',
            meetmanager_dot_v1_dot_meet__manager__pb2.GenerateReportRequest.SerializeToString,
            meetmanager_dot_v1_dot_meet__manager__pb2.GenerateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
